-- -------------------------------------------------------------------------------
--------- Template for the lab schema update scripts -----------------------------
-- Rules --
-- Create update script file (ex:lab_DBUpdate_S30.sql)under the \labcore\updates folder.
-- Do not use the lab schema name in any sql statements
-- At the end of the sprint add the new script to the lab_data_setup.sql batch file
-- ex: source ./updates/lab_DBUpdate_S30.sql;
-- --------------------------------------------------------------------------------


-- --------------------------------------------------------
-- Sprint Number
-- --------------------------------------------------------
-- ILT Number - Start -------------------------------------

-- Add your sql statements here..

-- ILT Number - End ---------------------------------------