//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.03 at 04:24:27 PM EDT 
//


package net.aegis.gateway.client.connect248.pd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for patientAddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patientAddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="patientStreetAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="patientStreetAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="patientCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="patientState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="patientZip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patientAddressType", propOrder = {
    "patientStreetAddress1",
    "patientStreetAddress2",
    "patientCity",
    "patientState",
    "patientZip"
})
public class PatientAddressType {

    @XmlElement(required = true)
    protected String patientStreetAddress1;
    @XmlElement(required = true)
    protected String patientStreetAddress2;
    @XmlElement(required = true)
    protected String patientCity;
    @XmlElement(required = true)
    protected String patientState;
    @XmlElement(required = true)
    protected String patientZip;

    /**
     * Gets the value of the patientStreetAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientStreetAddress1() {
        return patientStreetAddress1;
    }

    /**
     * Sets the value of the patientStreetAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientStreetAddress1(String value) {
        this.patientStreetAddress1 = value;
    }

    /**
     * Gets the value of the patientStreetAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientStreetAddress2() {
        return patientStreetAddress2;
    }

    /**
     * Sets the value of the patientStreetAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientStreetAddress2(String value) {
        this.patientStreetAddress2 = value;
    }

    /**
     * Gets the value of the patientCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientCity() {
        return patientCity;
    }

    /**
     * Sets the value of the patientCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientCity(String value) {
        this.patientCity = value;
    }

    /**
     * Gets the value of the patientState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientState() {
        return patientState;
    }

    /**
     * Sets the value of the patientState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientState(String value) {
        this.patientState = value;
    }

    /**
     * Gets the value of the patientZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientZip() {
        return patientZip;
    }

    /**
     * Sets the value of the patientZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientZip(String value) {
        this.patientZip = value;
    }

}
