//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.05 at 05:40:21 PM EDT 
//


package net.aegis.gateway.client.connect248.pd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for telephoneUseType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="telephoneUseType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="WP"/>
 *     &lt;enumeration value="HP"/>
 *     &lt;enumeration value="CP"/>
 *     &lt;enumeration value="OP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "telephoneUseType")
@XmlEnum
public enum TelephoneUseType {

    WP,
    HP,
    CP,
    OP;

    public String value() {
        return name();
    }

    public static TelephoneUseType fromValue(String v) {
        return valueOf(v);
    }

}
