//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.03 at 04:24:27 PM EDT 
//


package net.aegis.gateway.client.connect32.pd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.aegis.ri.ws.pd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.aegis.ri.ws.pd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PatientPD }
     * 
     */
    public PatientPD createPatientPD() {
        return new PatientPD();
    }

    /**
     * Create an instance of {@link PatientAddressesType }
     * 
     */
    public PatientAddressesType createPatientAddressesType() {
        return new PatientAddressesType();
    }

    /**
     * Create an instance of {@link PatientNamesType }
     * 
     */
    public PatientNamesType createPatientNamesType() {
        return new PatientNamesType();
    }

    /**
     * Create an instance of {@link PatientGivenNamesType }
     * 
     */
    public PatientGivenNamesType createPatientGivenNamesType() {
        return new PatientGivenNamesType();
    }

    /**
     * Create an instance of {@link PatientAddressType }
     * 
     */
    public PatientAddressType createPatientAddressType() {
        return new PatientAddressType();
    }

    /**
     * Create an instance of {@link PatientTelsType }
     * 
     */
    public PatientTelsType createPatientTelsType() {
        return new PatientTelsType();
    }

    /**
     * Create an instance of {@link PatientTelType }
     * 
     */
    public PatientTelType createPatientTelType() {
        return new PatientTelType();
    }

    /**
     * Create an instance of {@link PatientNameType }
     * 
     */
    public PatientNameType createPatientNameType() {
        return new PatientNameType();
    }

}
