//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.14 at 04:39:02 PM EDT 
//


package net.aegis.gateway.client.connect32.rd;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="initiatorPatientId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userFamilyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userGivenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userInitials" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="patientDocument" type="{}documentRD" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initiatorPatientId",
    "userFamilyName",
    "userGivenName",
    "userInitials",
    "userName",
    "patientDocument"
})
@XmlRootElement(name = "patientRD")
public class PatientRD {

    @XmlElement(required = true)
    protected String initiatorPatientId;
    @XmlElement(required = true)
    protected String userFamilyName;
    @XmlElement(required = true)
    protected String userGivenName;
    @XmlElement(required = true)
    protected String userInitials;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected List<DocumentRD> patientDocument;

    /**
     * Gets the value of the initiatorPatientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatorPatientId() {
        return initiatorPatientId;
    }

    /**
     * Sets the value of the initiatorPatientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatorPatientId(String value) {
        this.initiatorPatientId = value;
    }

    /**
     * Gets the value of the userFamilyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFamilyName() {
        return userFamilyName;
    }

    /**
     * Sets the value of the userFamilyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFamilyName(String value) {
        this.userFamilyName = value;
    }

    /**
     * Gets the value of the userGivenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserGivenName() {
        return userGivenName;
    }

    /**
     * Sets the value of the userGivenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserGivenName(String value) {
        this.userGivenName = value;
    }

    /**
     * Gets the value of the userInitials property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserInitials() {
        return userInitials;
    }

    /**
     * Sets the value of the userInitials property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserInitials(String value) {
        this.userInitials = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the patientDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patientDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatientDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentRD }
     * 
     * 
     */
    public List<DocumentRD> getPatientDocument() {
        if (patientDocument == null) {
            patientDocument = new ArrayList<DocumentRD>();
        }
        return this.patientDocument;
    }

}
