package net.aegis.mv.mockdata;

public enum TestScenario {
	
	PD_SUCCESS_SCENARIO,
	QD_SUCCESS_SCENARIO,
	RD_SUCCESS_SCENARIO,
	PD_FAILURE_SCENARIO,
	QD_FAILURE_SCENARIO,
	RD_FAILURE_SCENARIO,
	PD_SOAP_FAULT_SCENARIO,
	QD_SOAP_FAULT_SCENARIO,
	RD_SOAP_FAULT_SCENARIO;
		
}
