//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.07.15 at 01:46:13 PM EDT
//


package net.aegis.gateway.client.connect248.qd;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="initiatorPatientId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userFamilyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userGivenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userInitials" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="responderPatient" type="{}responderPatientQD" maxOccurs="unbounded"/>
 *         &lt;element name="documentParams">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="creationTimeInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="creationTimeFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="creationTimeTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="serviceStartTimeInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="serviceStartTimeFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="serviceStartTimeTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="serviceStopTimeInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="serviceStopTimeFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="serviceStopTimeTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="classCodeInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="classCodeList" type="{}classCodeListQD" maxOccurs="unbounded"/>
 *                   &lt;element name="statusInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="statusList" type="{}statusListQD" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initiatorPatientId",
    "userFamilyName",
    "userGivenName",
    "userInitials",
    "userName",
    "responderPatient",
    "documentParams"
})
@XmlRootElement(name = "patientQD")
public class PatientQD {

    @XmlElement(required = true)
    protected String initiatorPatientId;
    @XmlElement(required = true)
    protected String userFamilyName;
    @XmlElement(required = true)
    protected String userGivenName;
    @XmlElement(required = true)
    protected String userInitials;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected List<ResponderPatientQD> responderPatient;
    @XmlElement(required = true)
    protected PatientQD.DocumentParams documentParams;

    /**
     * Gets the value of the initiatorPatientId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInitiatorPatientId() {
        return initiatorPatientId;
    }

    /**
     * Sets the value of the initiatorPatientId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInitiatorPatientId(String value) {
        this.initiatorPatientId = value;
    }

    /**
     * Gets the value of the userFamilyName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUserFamilyName() {
        return userFamilyName;
    }

    /**
     * Sets the value of the userFamilyName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUserFamilyName(String value) {
        this.userFamilyName = value;
    }

    /**
     * Gets the value of the userGivenName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUserGivenName() {
        return userGivenName;
    }

    /**
     * Sets the value of the userGivenName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUserGivenName(String value) {
        this.userGivenName = value;
    }

    /**
     * Gets the value of the userInitials property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUserInitials() {
        return userInitials;
    }

    /**
     * Sets the value of the userInitials property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUserInitials(String value) {
        this.userInitials = value;
    }

    /**
     * Gets the value of the userName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the responderPatient property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responderPatient property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponderPatient().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResponderPatientQD }
     *
     *
     */
    public List<ResponderPatientQD> getResponderPatient() {
        if (responderPatient == null) {
            responderPatient = new ArrayList<ResponderPatientQD>();
        }
        return this.responderPatient;
    }

    /**
     * Gets the value of the documentParams property.
     *
     * @return
     *     possible object is
     *     {@link PatientQD.DocumentParams }
     *
     */
    public PatientQD.DocumentParams getDocumentParams() {
        return documentParams;
    }

    /**
     * Sets the value of the documentParams property.
     *
     * @param value
     *     allowed object is
     *     {@link PatientQD.DocumentParams }
     *
     */
    public void setDocumentParams(PatientQD.DocumentParams value) {
        this.documentParams = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="creationTimeInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="creationTimeFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="creationTimeTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="serviceStartTimeInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="serviceStartTimeFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="serviceStartTimeTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="serviceStopTimeInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="serviceStopTimeFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="serviceStopTimeTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="classCodeInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="classCodeList" type="{}classCodeListQD" maxOccurs="unbounded"/>
     *         &lt;element name="statusInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="statusList" type="{}statusListQD" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "creationTimeInd",
        "creationTimeFrom",
        "creationTimeTo",
        "serviceStartTimeInd",
        "serviceStartTimeFrom",
        "serviceStartTimeTo",
        "serviceStopTimeInd",
        "serviceStopTimeFrom",
        "serviceStopTimeTo",
        "classCodeInd",
        "classCodeList",
        "statusInd",
        "statusList"
    })
    public static class DocumentParams {

        @XmlElement(required = true)
        protected String creationTimeInd;
        @XmlElement(required = true)
        protected String creationTimeFrom;
        @XmlElement(required = true)
        protected String creationTimeTo;
        @XmlElement(required = true)
        protected String serviceStartTimeInd;
        @XmlElement(required = true)
        protected String serviceStartTimeFrom;
        @XmlElement(required = true)
        protected String serviceStartTimeTo;
        @XmlElement(required = true)
        protected String serviceStopTimeInd;
        @XmlElement(required = true)
        protected String serviceStopTimeFrom;
        @XmlElement(required = true)
        protected String serviceStopTimeTo;
        @XmlElement(required = true)
        protected String classCodeInd;
        @XmlElement(required = true)
        protected List<ClassCodeListQD> classCodeList;
        @XmlElement(required = true)
        protected String statusInd;
        @XmlElement(required = true)
        protected List<StatusListQD> statusList;

        /**
         * Gets the value of the creationTimeInd property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCreationTimeInd() {
            return creationTimeInd;
        }

        /**
         * Sets the value of the creationTimeInd property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCreationTimeInd(String value) {
            this.creationTimeInd = value;
        }

        /**
         * Gets the value of the creationTimeFrom property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCreationTimeFrom() {
            return creationTimeFrom;
        }

        /**
         * Sets the value of the creationTimeFrom property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCreationTimeFrom(String value) {
            this.creationTimeFrom = value;
        }

        /**
         * Gets the value of the creationTimeTo property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCreationTimeTo() {
            return creationTimeTo;
        }

        /**
         * Sets the value of the creationTimeTo property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCreationTimeTo(String value) {
            this.creationTimeTo = value;
        }

        /**
         * Gets the value of the serviceStartTimeInd property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getServiceStartTimeInd() {
            return serviceStartTimeInd;
        }

        /**
         * Sets the value of the serviceStartTimeInd property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setServiceStartTimeInd(String value) {
            this.serviceStartTimeInd = value;
        }

        /**
         * Gets the value of the serviceStartTimeFrom property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getServiceStartTimeFrom() {
            return serviceStartTimeFrom;
        }

        /**
         * Sets the value of the serviceStartTimeFrom property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setServiceStartTimeFrom(String value) {
            this.serviceStartTimeFrom = value;
        }

        /**
         * Gets the value of the serviceStartTimeTo property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getServiceStartTimeTo() {
            return serviceStartTimeTo;
        }

        /**
         * Sets the value of the serviceStartTimeTo property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setServiceStartTimeTo(String value) {
            this.serviceStartTimeTo = value;
        }

        /**
         * Gets the value of the serviceStopTimeInd property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getServiceStopTimeInd() {
            return serviceStopTimeInd;
        }

        /**
         * Sets the value of the serviceStopTimeInd property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setServiceStopTimeInd(String value) {
            this.serviceStopTimeInd = value;
        }

        /**
         * Gets the value of the serviceStopTimeFrom property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getServiceStopTimeFrom() {
            return serviceStopTimeFrom;
        }

        /**
         * Sets the value of the serviceStopTimeFrom property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setServiceStopTimeFrom(String value) {
            this.serviceStopTimeFrom = value;
        }

        /**
         * Gets the value of the serviceStopTimeTo property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getServiceStopTimeTo() {
            return serviceStopTimeTo;
        }

        /**
         * Sets the value of the serviceStopTimeTo property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setServiceStopTimeTo(String value) {
            this.serviceStopTimeTo = value;
        }

        /**
         * Gets the value of the classCodeInd property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getClassCodeInd() {
            return classCodeInd;
        }

        /**
         * Sets the value of the classCodeInd property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setClassCodeInd(String value) {
            this.classCodeInd = value;
        }

        /**
         * Gets the value of the classCodeList property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the classCodeList property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClassCodeList().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ClassCodeListQD }
         *
         *
         */
        public List<ClassCodeListQD> getClassCodeList() {
            if (classCodeList == null) {
                classCodeList = new ArrayList<ClassCodeListQD>();
            }
            return this.classCodeList;
        }

        /**
         * Gets the value of the statusInd property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getStatusInd() {
            return statusInd;
        }

        /**
         * Sets the value of the statusInd property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setStatusInd(String value) {
            this.statusInd = value;
        }

        /**
         * Gets the value of the statusList property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the statusList property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStatusList().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StatusListQD }
         *
         *
         */
        public List<StatusListQD> getStatusList() {
            if (statusList == null) {
                statusList = new ArrayList<StatusListQD>();
            }
            return this.statusList;
        }

    }

}
